### ISSUE TITLE
Tag Searching

### ISSUE THREAD

**Issue by Sir-AL** [gabriel-dehan/dyson-sphere-blueprints#46]
I'm not sure if your database requesting is setup to easily do this, but it would be nice if the tags were searched for with AND instead of OR .The more values you put in, the more results you get, which seems to be kind of pointless in most use cases. Unless I'm missing something. If it was MYSQL DB I know it would be a easy change, but I know absolutely nothing about ruby or what DB system you use since all my programming knowledge is self taught from 10+ years ago.

**Comment by dvhg** [comment]
Agreed. I also found this unintuitive since the other filter categories (author, title, etc.) are AND'd with the tags but individual tags are OR'd. I would expect multiple tags to narrow a search rather than expand it. I opened a small PR to fix this; please feel free to close it if you disagree. Thanks!
